version: "3.9"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aroma/data/mariadb
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aroma/data/wordpress

networks:
  inception_network:

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception_network
    volumes:
      - wp_volume:/var/www/
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    environment:
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception_network
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
