version: "3.9"

volumes:
  db_volume:
    driver: local
    name:
      db_volume
    driver_opts:
      type: volume
      device: /home/aroma/data/db_vol
  wp_volume:
    driver: local
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: /home/aroma/data/wp_vol

services:
  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html

  wordpress:
    build: requirements/wordpress
      #image: wordpress:latest
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'hello42'
      MYSQL_USER: 'temporary'
      MYSQL_PASSWORD: 'temporary'
      MYSQL_DATABASE: 'wordpress'
    #temporary
    ports:
      - "3306:3306"
