version: "3.9"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aroma/data/mariadb
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aroma/data/wordpress

networks:
  inception_network:

services:
  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - inception_network
    volumes:
      - wp_volume:/var/www/

  mariadb:
    build: requirements/mariadb
    #image: mariadb
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    networks:
      - inception_network
    volumes:
      - db_volume:/var/lib/mysql
